### ISSUE TITLE
JS test feedback

### ISSUE THREAD

**Issue by CK-HYF-DK** [somayehdvr/JS-test#1]
Via Svetlana (Mærsk)

Great job! Small comments: In the 1st exercise, no need for new line while printing the dishes, it would work the same if you wrote without "\n". In the 2nd exercise, no need for p as empty array, you could insert all paragraphs in the for loop. You could also use forEach instead of for https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach .

**Comment by somayehdvr** [comment]
Thank you for the comments. I have made the changes. But for the foreach also I need to define i because we need only the first three users.
